바이오/헬스케어 지수입니다.

나스닥 바이오테크놀로지 지수와 미국 FDA 신약 허가 일정이 있습니다.

1. 나스닥 바이오테크놀로지 지수

In [ ]:
!pip install --upgrade --force-reinstall numpy
!pip install --upgrade --force-reinstall yfinanc 
! pip install numpy<2
!pip install numpy==1.24.4
 #아래 코드 오류가 나면 이 코드 돌려주세요..

In [4]:
import yfinance as yf
import pandas as pd

ticker = 'NBI'
data = yf.download(ticker, period='60d')

nbi = data.reset_index()[['Date', 'Close']]
nbi.columns = ['날짜', '종가']

nbi

C:\Users\mcdor\AppData\Local\Temp\ipykernel_14548\1264974287.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker, period='60d')
[*********************100%***********************]  1 of 1 completed

           날짜           종가
0  2025-04-08  3731.850098
1  2025-04-09  3928.600098
2  2025-04-10  3774.989990
3  2025-04-11  3909.949951
4  2025-04-15  4010.459961
5  2025-04-16  3931.860107
6  2025-04-17  3968.909912
7  2025-04-21  3943.110107
8  2025-04-22  4048.229980
9  2025-04-23  4116.149902
10 2025-04-24  4190.580078
11 2025-04-25  4131.379883
12 2025-04-28  4184.770020
13 2025-04-29  4195.180176
14 2025-04-30  4260.419922
15 2025-05-01  4209.029785
16 2025-05-02  4266.279785
17 2025-05-05  4237.669922
18 2025-05-06  3981.889893
19 2025-05-07  3994.270020
20 2025-05-08  3985.139893
21 2025-05-09  3905.729980
22 2025-05-12  4071.070068
23 2025-05-13  3993.520020
24 2025-05-14  3915.199951
25 2025-05-15  4002.429932
26 2025-05-16  4066.209961
27 2025-05-19  4114.029785
28 2025-05-20  4177.939941
29 2025-05-21  4093.800049
30 2025-05-22  4081.699951
31 2025-05-23  4084.750000
32 2025-05-27  4122.620117
33 2025-05-28  4086.219971
34 2025-05-29  4170.990234
35 2025-05-30  4079.129883
36 2025-06-02  4145.299805
37 2025-06-03  4186.180176
38 2025-06-04  4183.470215
39 2025-06-05  4181.669922
40 2025-06-06  4254.939941
41 2025-06-09  4273.879883
42 2025-06-10  4312.319824
43 2025-06-11  4275.459961
44 2025-06-12  4318.899902
45 2025-06-13  4283.229980
46 2025-06-16  4274.120117
47 2025-06-17  4193.129883
48 2025-06-18  4211.890137
49 2025-06-20  4199.529785
50 2025-06-23  4179.479980
51 2025-06-24  4261.120117
52 2025-06-25  4232.379883
53 2025-06-26  4240.299805
54 2025-06-27  4224.520020
55 2025-06-30  4227.680176
56 2025-07-01  4260.000000
57 2025-07-02  4329.410156
58 2025-07-03  4351.270020

2. 미국 FDA 신약 허가 일정

In [12]:
import requests
import pandas as pd

url = "https://api.fda.gov/drug/drugsfda.json"
params = {'limit': 5}

response = requests.get(url, params=params)
data = response.json()

approval_list = []
for item in data.get('results', []):
    app_num = item.get('application_number')
    sponsor = item.get('sponsor_name')
    for product in item.get('products', []):
        brand_name = product.get('brand_name')
        
        # submission 배열 안에서 승인일 찾기
        approval_date = None
        submissions = product.get('submission', [])
        for sub in submissions:
            # 승인일이 있으면 그걸로 설정
            if 'approval_date' in sub:
                approval_date = sub['approval_date']
                break  # 가장 첫 승인일만 사용
        
        approval_list.append({
            '신약명': brand_name,
            '승인일': approval_date,
            '신청번호': app_num,
            '제약사': sponsor
        })

df = pd.DataFrame(approval_list)
print(df)

                                    신약명   승인일        신청번호                 제약사
0                             OFLOXACIN  None  ANDA076182                TEVA
1                             OFLOXACIN  None  ANDA076182                TEVA
2                             OFLOXACIN  None  ANDA076182                TEVA
3              LIDOCAINE AND PRILOCAINE  None  ANDA076453      FOUGERA PHARMS
4   FLUCONAZOLE IN SODIUM CHLORIDE 0.9%  None  ANDA076736  HIKMA FARMACEUTICA
5                            CILOSTAZOL  None  ANDA077028   ACTAVIS ELIZABETH
6                            CILOSTAZOL  None  ANDA077028   ACTAVIS ELIZABETH
7                            CARVEDILOL  None  ANDA077316  NORVIUM BIOSCIENCE
8                            CARVEDILOL  None  ANDA077316  NORVIUM BIOSCIENCE
9                            CARVEDILOL  None  ANDA077316  NORVIUM BIOSCIENCE
10                           CARVEDILOL  None  ANDA077316  NORVIUM BIOSCIENCE

-> 승인일이 다 none으로 나오고, 신약 승인 목표일 같은 경우에는 직접 계속 찾아보면서 크롤링을 해야해서 하기 좀 많이 어렵습니다.