원자재 지수

WTI 원유 선물 지수입니다.

1. WTI

In [3]:
!pip install --upgrade --force-reinstall numpy
!pip install --upgrade --force-reinstall yfinanc #아래 코드 에러나면 돌려주세요.

Defaulting to user installation because normal site-packages is not writeable
Collecting numpy
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/6b/fb/bb613f4122c310a13ec67585c70e14b03bfc7ebabd24f4d5138b97371d7c/numpy-2.3.1-cp311-cp311-win_amd64.whl.metadata
  Using cached numpy-2.3.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.3.1-cp311-cp311-win_amd64.whl (13.0 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.3.1
    Uninstalling numpy-2.3.1:
      Successfully uninstalled numpy-2.3.1

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'C:\Users\mcdor\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: Could not install packages due to an OSError: [WinError 5] 액세스가 거부되었습니다: 'C:\\Users\\mcdor\\AppData\\Roaming\\Python\\Python311\\site-packages\\~~mpy.libs\\libscipy_openblas64_-13e2df515630b4a41f92893938845698.dll'
Check the permissions.

Defaulting to user installation because normal site-packages is not writeable

ERROR: Invalid requirement: '#아래'

In [1]:
! pip install numpy<2 #아래 코드 오류가 나면 이 코드 돌려주세요.

������ ������ ã�� �� �����ϴ�.

In [6]:
import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta

# WTI 원유 선물 티커
ticker = 'CL=F'

# 90일치 데이터 수집
raw = yf.download(ticker, period='90d', interval='1d')

# 날짜 및 종가만 추출 후 필터링
TWI = raw.reset_index()[['Date', 'Close']]
TWI.columns = ['날짜', '가격']

# 오늘 기준 60일 이내 데이터만 남기기
cutoff_date = datetime.today() - timedelta(days=60)
TWI = TWI[TWI['날짜'] >= cutoff_date].reset_index(drop=True)
TWI

C:\Users\mcdor\AppData\Local\Temp\ipykernel_17872\1047404982.py:9: FutureWarning: YF.download() has changed argument auto_adjust default to True
  raw = yf.download(ticker, period='90d', interval='1d')
[*********************100%***********************]  1 of 1 completed

           날짜         가격
0  2025-05-06  59.090000
1  2025-05-07  58.070000
2  2025-05-08  59.910000
3  2025-05-09  61.020000
4  2025-05-12  61.950001
5  2025-05-13  63.669998
6  2025-05-14  63.150002
7  2025-05-15  61.619999
8  2025-05-16  62.490002
9  2025-05-19  62.689999
10 2025-05-20  62.560001
11 2025-05-21  61.570000
12 2025-05-22  61.200001
13 2025-05-23  61.529999
14 2025-05-27  60.889999
15 2025-05-28  61.840000
16 2025-05-29  60.939999
17 2025-05-30  60.790001
18 2025-06-02  62.520000
19 2025-06-03  63.410000
20 2025-06-04  62.849998
21 2025-06-05  63.369999
22 2025-06-06  64.580002
23 2025-06-09  65.290001
24 2025-06-10  64.980003
25 2025-06-11  68.150002
26 2025-06-12  68.040001
27 2025-06-13  72.980003
28 2025-06-16  71.769997
29 2025-06-17  74.839996
30 2025-06-18  75.139999
31 2025-06-20  74.930000
32 2025-06-23  68.510002
33 2025-06-24  64.370003
34 2025-06-25  64.919998
35 2025-06-26  65.239998
36 2025-06-27  65.519997
37 2025-06-30  65.110001
38 2025-07-01  65.449997
39 2025-07-02  67.449997
40 2025-07-03  67.000000
41 2025-07-04  66.300003