인터넷/게임 지수

다우존스 인터넷 종합 지수가 있어요

1. 다우존스

In [ ]:
!pip install --upgrade --force-reinstall numpy
!pip install --upgrade --force-reinstall yfinanc 
! pip install numpy<2
!pip install numpy==1.24.4
 #아래 코드 오류가 나면 이 코드 돌려주세요..

In [10]:
import yfinance as yf

# FDN ETF 데이터 60일치 다운로드
data = yf.download('FDN', period='60d')

# 날짜 인덱스를 컬럼으로 변경하고, 날짜와 종가 컬럼만 선택
fdn = data.reset_index()[['Date', 'Close']]

# 컬럼명 한글로 변경
fdn.columns = ['날짜', '종가']

fdn

C:\Users\mcdor\AppData\Local\Temp\ipykernel_14544\523272180.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download('FDN', period='60d')
[*********************100%***********************]  1 of 1 completed

           날짜          종가
0  2025-04-08  200.289993
1  2025-04-09  221.949997
2  2025-04-10  213.309998
3  2025-04-11  215.570007
4  2025-04-14  215.729996
5  2025-04-15  216.589996
6  2025-04-16  212.669998
7  2025-04-17  211.929993
8  2025-04-21  206.330002
9  2025-04-22  212.729996
10 2025-04-23  218.539993
11 2025-04-24  226.369995
12 2025-04-25  229.190002
13 2025-04-28  228.949997
14 2025-04-29  231.130005
15 2025-04-30  231.220001
16 2025-05-01  234.759995
17 2025-05-02  238.839996
18 2025-05-05  238.339996
19 2025-05-06  236.460007
20 2025-05-07  235.800003
21 2025-05-08  238.699997
22 2025-05-09  237.169998
23 2025-05-12  246.669998
24 2025-05-13  250.679993
25 2025-05-14  252.259995
26 2025-05-15  251.550003
27 2025-05-16  253.309998
28 2025-05-19  253.220001
29 2025-05-20  251.630005
30 2025-05-21  249.330002
31 2025-05-22  251.270004
32 2025-05-23  247.550003
33 2025-05-27  251.740005
34 2025-05-28  250.929993
35 2025-05-29  249.570007
36 2025-05-30  251.199997
37 2025-06-02  253.089996
38 2025-06-03  254.250000
39 2025-06-04  256.799988
40 2025-06-05  257.619995
41 2025-06-06  260.809998
42 2025-06-09  260.420013
43 2025-06-10  259.760010
44 2025-06-11  258.799988
45 2025-06-12  258.070007
46 2025-06-13  254.100006
47 2025-06-16  258.359985
48 2025-06-17  256.480011
49 2025-06-18  255.740005
50 2025-06-20  253.630005
51 2025-06-23  256.589996
52 2025-06-24  261.070007
53 2025-06-25  260.339996
54 2025-06-26  264.369995
55 2025-06-27  267.250000
56 2025-06-30  269.329987
57 2025-07-01  265.869995
58 2025-07-02  265.890015
59 2025-07-03  269.019989

->다우존스 관련해서 하려했는데 api에서 제공을 제대로 안 해줍니다. 따라서 다우존스 인터넷 컴포지트 지수를 추종하는 etf로 변경하였으며, 이게 더 거래량이 많다고 하네요.